name: Deploy to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'  # Only trigger when web folder changes
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies
        working-directory: ./web
        run: npm ci

      - name: Build Next.js application
        working-directory: ./web
        run: npm run build

      - name: Create deployment package
        working-directory: ./web
        run: |
          mkdir -p deploy
          cp -r .next/standalone/. deploy/
          mkdir -p deploy/.next/static
          cp -r .next/static/. deploy/.next/static/
          cp -r public deploy/public
          
          # Create .env.production
          cat > deploy/.env.production << 'EOF'
          PORT=3001
          POSTGRES_URL="postgres://gift_admin:password123@localhost:5432/gift_orders"
          POSTGRES_URL_NON_POOLING="postgres://gift_admin:password123@localhost:5432/gift_orders"
          NEXT_PUBLIC_API_MOCKING="disabled"
          NODE_ENV="production"
          EOF
          
          # Create tarball
          cd deploy
          tar -czf ../joytree-app.tar.gz .
          cd ..

          - name: Configure SSH
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2-key.pem
            
            # Remove any carriage returns or extra whitespace
            sed -i 's/\r$//' ~/.ssh/ec2-key.pem
            
            # Ensure proper line endings
            chmod 600 ~/.ssh/ec2-key.pem
            
            # Add host to known_hosts
            ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
            
            # Test the key format
            ssh-keygen -l -f ~/.ssh/ec2-key.pem || echo "Key format check failed"

      - name: Upload to EC2
        run: |
          scp -i ~/.ssh/ec2-key.pem \
            web/joytree-app.tar.gz \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/

      - name: Deploy on EC2
        run: |
          ssh -i ~/.ssh/ec2-key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'ENDSSH'
            cd ~
            rm -rf joytree-app-old
            mv joytree-app joytree-app-old 2>/dev/null || true
            mkdir joytree-app
            cd joytree-app
            tar -xzf ~/joytree-app.tar.gz
            
            # Restart PM2
            pm2 restart joytree-gift || PORT=3001 pm2 start server.js --name joytree-gift -i 1
            pm2 save
            
            # Verify deployment
            sleep 5
            if pm2 list | grep -q "joytree-gift.*online"; then
              echo "✅ Deployment successful!"
            else
              echo "❌ Deployment failed!"
              pm2 logs joytree-gift --lines 50
              exit 1
            fi
          ENDSSH

      - name: Clean up
        if: always()
        run: rm -f ~/.ssh/ec2-key.pem

      - name: Deployment notification
        if: success()
        run: |
          echo "🎉 Deployment completed successfully!"
          echo "🌐 Application is live at: http://${{ secrets.EC2_HOST }}"